vich_uploader:
    db_driver: orm

    mappings:
        books_cover:
            uri_prefix: /images/books_cover
            upload_destination: '%kernel.project_dir%/public/images/books_cover'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
